char:
  1m: "一"
  2m: "二"
  3m: "三"
  4m: "四"
  5m: "五"
  6m: "六"
  7m: "七"
  8m: "八"
  9m: "九"
  1p: "①"
  2p: "②"
  3p: "③"
  4p: "④"
  5p: "⑤"
  6p: "⑥"
  7p: "⑦"
  8p: "⑧"
  9p: "⑨"
  1s: "１"
  2s: "２"
  3s: "３"
  4s: "４"
  5s: "５"
  6s: "６"
  7s: "７"
  8s: "８"
  9s: "９"
  1z: "東"
  2z: "南"
  3z: "西"
  4z: "北"
  5z: "白"
  6z: "発"
  7z: "中"
